default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5

development:
  <<: *default
  database: railsformbuilder_development

test:
  <<: *default
  database: railsformbuilder_test

production:
  <<: *default
  database: railsformbuilder_production
  username: railsformbuilder
  password: <%= ENV['RAILS4BASE_DATABASE_PASSWORD'] %>
