default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: 5

development:
  <<: *default
  database: rails4base_development

test:
  <<: *default
  database: rails4base_test

production:
  <<: *default
  database: rails4base_production
  username: rails4base
  password: <%= ENV['RAILS4BASE_DATABASE_PASSWORD'] %>
