# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e73424c25067cfbab35fd7cb5369cc4952863b4e25ce2306e9af707254d4145022b4194d9fd584c16d1bae5e95ca1621b47c464daa4527546f544f501bf3c615

test:
  secret_key_base: a74067a32ec7b69d3f756e8ad5cbc1a1a552b1bf7b2326d95cfc9a28fd2d7e9f057bbb18b81dfb2f8337ad85250757d71c5097f602a81bc08eee76faf079ca2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
